### ISSUE TITLE
Failed to Build Wheels for xformers and Compatibility

### ISSUE THREAD

**Issue by nhtlongcs** [facebookresearch/lingua#19]
I'm encountering issues while trying to install `xformers`. The installation process fails with the following error:

```
ERROR: Failed building wheel for xformers
Running setup.py clean for xformers
Failed to build xformers
ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)
```

To resolve this, I attempted to install a different version of `xformers`, but this required downgrading `pytorch` to version 2.4. However, this caused compatibility issues in lingua. Specifically, the following imports in `lingua/distributed.py` failed:

```python
from torch.utils.checkpoint import (
    create_selective_checkpoint_contexts,
    CheckpointPolicy,
)
```

These functions are not available in `pytorch` 2.4, as confirmed in the [official documentation](https://pytorch.org/docs/2.4/search.html?q=CheckpointPolicy&check_keywords=yes&area=default#).

Is there an official way to install xformers without downgrading pytorch, or a workaround to maintain compatibility with the latest features?

**Comment by SeunghyunSEO** [comment]
how bout following [these lines](https://github.com/facebookresearch/lingua/blob/main/setup/create_env.sh#L34-L38)? 
it works to me

```python
pip install torch --index-url https://download.pytorch.org/whl/cu121
pip install ninja
pip install git+https://github.com/facebookresearch/xformers.git@d3948b5cb9a3711032a0ef0e036e809c7b08c1e0#egg=xformers
pip install --requirement requirements.txt
```

**Comment by nhtlongcs** [comment]
Thank you @SeunghyunSEO. Unfortunately, this approach didn't work for me. Following the instructions caused PyTorch to automatically downgrade to version 2.4.0 during the xformers build process.

**Comment by lopezpaz** [comment]
Delegating to `xformers` community, but please feel free to re-open if there is an integration issue with `lingua`.

**Comment by mathuvu** [comment]
There is now a pre built version of xformers for pytorch 2.5, we will soon update the requirement to make it easier to install.

**Comment by Abra-web** [comment]
What is the current situation on this? I am currently trying to install the last version "xformers 0.0.28.post3" but it gives me the error
"
ERROR: Failed building wheel for xformers
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects
"

**Comment by ianjali** [comment]
1. First, ensure LLVM is linked properly 
`brew link llvm`
2. Set these environment variables before installing
`export CC=/opt/homebrew/opt/llvm/bin/clang`
`export CXX=/opt/homebrew/opt/llvm/bin/clang++`
3. Try installing xformers again with these environment variables:
`CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++ pip install xformers`
