### ISSUE TITLE
More Config Examples

### ISSUE THREAD

**Issue by BeeGass** [facebookresearch/lingua#3]
It would be really great if you could add config examples for the other models other than llama. Would definitely help with understanding how to structure the yaml as well as how it interfaces with the rest of the codebase

**Comment by BadrYoubiIdrissi** [comment]
Hi ! Each app has its own configs folder with example configs. We are planning to add READMEs to each app also to make it easier 

apps/fastRNN/hawk/configs/hawk_1b.yaml
apps/fastRNN/minGRU/configs/hawk_1b.yaml
apps/mtp/configs
etc...

**Comment by BeeGass** [comment]
My apologies. I was looking at `apps/main/configs` and thought that was the extent of the configs. Thanks so much.
