### ISSUE TITLE
Loading from consolidated checkpoint

### ISSUE THREAD

**Issue by SpirinEgor** [facebookresearch/lingua#36]
Hello!
Thank you for awesome framework! 🔥

Looking into checkpointing system, it seems to handle resuming training from DCP, but I'm wondering how to load consolidated checkpoint? I see `init_ckpt_path` arg, but it failed to load consolidated checkpoint when model is compiled and distributed 🫠

**Comment by SpirinEgor** [comment]
Somehow I dealt with it, my current workaround:
1. Convert consolidated checkpoint into distributed format
```python
from torch.distributed.checkpoint.format_utils import torch_save_to_dcp
torch_save_to_dcp(CONSOLIDATED_CKPT_PATH, DCP_DIR_PATH)
```
2. Manually create `params.json`
```json
{"model": {...}}
```
3. Fix checkpoint loading in `apps.main.train`, lines ~244-250
```python
if args.checkpoint.init_ckpt_path:
    st_dict = get_model_state_dict(model)
    dcp_load(st_dict, checkpoint_id=args.checkpoint.init_ckpt_path)
    set_model_state_dict(model, st_dict)
```
`get_model_state_dict` and `set_model_state_dict` are functions from `torch.distributed.checkpoint.state_dict` and `dcp_load` is a `load` function from `torch.distributed.checkpoint`

Note that by default, `lingua` creates a consolidated checkpoint with `model` and `optimizer` keys in the state dictionary. However, the consolidated checkpoint of llama models on platforms like Hugging Face contains only model weights. Therefore, you always need to accurately handle the loaded state dictionary.

**Comment by Golovneva** [comment]
I had the same problem, thank you for posting the solution. Hope it will be fixed in main.

**Comment by mathuvu** [comment]
I've added some helper function for loading. Unfortunately, it is stil needed to convert to dcp checkpoint format before loading with `torch_save_to_dcp`. Hope it's better/clearer now.
