### ISSUE TITLE
Distributed Shampoo

### ISSUE THREAD

**Issue by Ryu1845** [facebookresearch/lingua#37]
Hey, great work with lingua ! I was wondering if you'd consider adding support for the distributed shampoo optimizer.

**Comment by faresobeid** [comment]
Only real thing that would need changing is allowing different optimisers for different weights (emb, lm head, and 1D weights with adam then rest with adam or shampoo,...). Done here for reference https://github.com/KellerJordan/modded-nanogpt

**Comment by sksq96** [comment]
You can also use this repo from facebook: https://github.com/facebookresearch/optimizers

```import torch
from distributed_shampoo.distributed_shampoo import DistributedShampoo
from distributed_shampoo.shampoo_types import AdamGraftingConfig

model = ...  # Instantiate model

optim = DistributedShampoo(
    model.parameters(),
    lr=1e-3,
    betas=(0.9, 0.999),
    epsilon=1e-8,
    grafting_config=AdamGraftingConfig(
        beta2=0.999,
        epsilon=1e-8,
    ),
)```

**Comment by lopezpaz** [comment]
Thank you @sksq96 for a solution.
