### ISSUE TITLE
global depth init std factor seems incorrect 

### ISSUE THREAD

**Issue by SeunghyunSEO** [facebookresearch/lingua#39]
following [this line](https://github.com/facebookresearch/lingua/blob/a7cdf138d9196a9280b487be1efadf5c67ff33f0/lingua/transformer.py#L400-L403), all qkv and o projection got `std/sqrt(2*num_layers)`

```
            it_std = init_std or (self.dim ** (-0.5))
            init_std = init_std / factor
            for w in [self.wq, self.wk, self.wv, self.wo]:
                nn.init.trunc_normal_(
                    w.weight,
                    mean=0.0,
                    std=init_std,
                    a=-3 * init_std,
                    b=3 * init_std,
                )
```

and it's not gpt2 thing.
i think we should fix this like below (and fix FFN too)
or we got very low std and it does not gaurantee variance not increased or decresead at initialization

```
            init_std = init_std or (self.dim ** (-0.5))
            for w in [self.wq, self.wk, self.wv]:
                nn.init.trunc_normal_(
                    w.weight,
                    mean=0.0,
                    std=init_std,
                    a=-3 * init_std,
                    b=3 * init_std,
                )
            nn.init.trunc_normal_(
                self.wo.weight,
                mean=0.0,
                std=init_std / factor,
                a=-3 * init_std,
                b=3 * init_std,
            )
```

**Comment by mathuvu** [comment]
I've run some experiments at 1B scale and it's seems to not change much overall results. But true, that it sounds more natural to downscale only the last linear before the residual, so your suggestion is in PR #47 which will be merge in main soon.

Here is the learning curve of each experiments:
<img width="1057" alt="Screenshot 2024-11-05 at 14 24 37" src="https://github.com/user-attachments/assets/d4d54c77-15f6-40e1-a92a-e06cce87a42d">

**Comment by SeunghyunSEO** [comment]
> I've run some experiments at 1B scale and it's seems to not change much overall results. But true, that it sounds more natural to downscale only the last linear before the residual, so your suggestion is in PR #47 which will be merge in main soon.
> 
> 
> 
> Here is the learning curve of each experiments:
> 
> <img width="1057" alt="Screenshot 2024-11-05 at 14 24 37" src="https://github.com/user-attachments/assets/d4d54c77-15f6-40e1-a92a-e06cce87a42d">

nice!
i think it's acceptable that it does not show large difference. to my best knowledge, it's fine to use common 0.02 std for 7b is fine (relatively small? compared to fan in variance), and there are some models like deepseek that used 0.005 for larger size model, but it still have much smaller than fanin variance.
but what i want to talk is that it's not what you intention, and it has potential issue that it shifts optimal hparams like lr i guess :)
