### ISSUE TITLE
Potential bug in main generate.py

### ISSUE THREAD

**Issue by akhauriyash** [facebookresearch/lingua#44]
Hello,

![image](https://github.com/user-attachments/assets/3ef41571-33d7-4610-b5db-3e45317814bb)

I was going through the code, and wanted to cross check, should the KVCache have module.n_kv_heads instead of n_heads? 

If not, then  I suspect that these lines should come AFTER repeat_kv... 

```
        if hasattr(self, "kv_cache"):
            xk, xv = self.kv_cache.update(xk, xv, tok_idx)
```

Please feel free to close the issue if I am incorrect.

Thanks

**Comment by mathuvu** [comment]
That's a good catch! I've fixed this in #47. Thank you for your feedback.
