### ISSUE TITLE
Better Documentation on Resuming

### ISSUE THREAD

**Issue by Hprairie** [facebookresearch/lingua#53]
I was wondering if there were any strong examples of resuming a training run that failed for whatever reason. I'm also curious if `stool` could be expanded to support that functionality. 

Thanks for such a great repo, been super fun to hack around with it!

**Comment by mathuvu** [comment]
The process works as follows: when a run is relaunched, the checkpoint manager scans all checkpoints in the checkpoint folder and reloads the most recent one based on the step number. This means that if the job is preempted or requeued by SLURM, it will automatically reload from the last checkpoint.

If the job crashes for some reason and you are using stool to launch it, simply run `sbatch /your_dump_dir/submit.slurm` to restart the job; the checkpoint manager will handle reloading automatically. The same approach applies to evaluation jobs. To relaunch an evaluation, use `sbatch /your_dump_dir/evals/your_eval_step/submit.slurm`. This works if the `eval_on_gpus `parameter is set to a non-null value (e.g.,` eval_on_gpus: 8`), which indicates that the evaluation job should be run on a separate job using 8 GPUs.

**Comment by Hprairie** [comment]
Thank you, really helps. Would say that putting this in the readme would be super helpful for others. Thanks again!
