### ISSUE TITLE
How data is sampled?

### ISSUE THREAD

**Issue by macabdul9** [facebookresearch/lingua#55]
I want to train a model for one pass (1 epoch) on fineweb_edu_10bt_shuffled. Should I pass nSteps in the config which is:
`nSteps = nExamples // (batch_size * nDevice * nAccumulation)` if not how else I can ensure my model is trained on all of fineweb_edu_10bt_shuffled for at least 1 epoch (exactly).

**Comment by macabdul9** [comment]
Thanks @mathuvu  for your comment. 

I have a follow-up. 

So if I have `nDevices << nchunks` then the seen nchunks (number .jsonl files) would be just nDevices and training will loop over on portion of these chunks (`== nDevices`) defined in config until it completes `nSteps`? 

```
data:
  root_dir: data/
  sources:
    fineweb_edu_10bt_shuffled: 1.0
```

If so - the best way to ensure that model is seeing all of `fineweb_edu_10bt`  data (or any other data) is to process it first into nChunks same as `nDevices`? Can you please confirm? Thanks in advance.

**Comment by mathuvu** [comment]
> So if I have nDevices << nchunks then the seen nchunks (number .jsonl files) would be just nDevices and training will loop over on portion of these chunks (== nDevices) defined in config until it completes nSteps?

Yes, it will loop on a subset of the data

> If so - the best way to ensure that model is seeing all of fineweb_edu_10bt data (or any other data) is to process it first into nChunks same as nDevices?

You can put `nchunks` to 1 if you want to make things easier or `nchunks` == nDevices.

**Comment by mathuvu** [comment]
A paragraph has been added in readme. Thank you for your feedback!
