### ISSUE TITLE
Unable to run debug code

### ISSUE THREAD

**Issue by distributedstatemachine** [facebookresearch/lingua#6]
## Description

I am unable to launch run lingua locally . 

I follow this 

```shell
# if you want to launch locally you can use torchrun
torchrun --nproc-per-node 8 -m apps.main.train config=apps/main/configs/debug.yaml
```

It expects a `tokenizers/tokenizer_final_32k.minus_inf_ws.model` file, and there arent instructions on how to load this . 

## Expected Behaviour

- execute `torchrun --nproc-per-node 8 -m apps.main.train config=apps/main/configs/debug.yaml`. 
- training runs
## Actual Behaviour
- execute `torchrun --nproc-per-node 8 -m apps.main.train config=apps/main/configs/debug.yaml`. 
- run crashes

## Stack Trace

```
tokenizers/tokenizer_final_32k.minus_inf_ws.model^
^^  File "/home/ubuntu/lingua/lingua/tokenizer.py", line 94, in __init__
^^^^^^^^^^^^^    ^assert os.path.isfile(model_path), model_path^
^^^^
  AssertionError :  tokenizers/tokenizer_final_32k.minus_inf_ws.model 
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: tokenizers/tokenizer_final_32k.minus_inf_ws.model
W1019 16:14:33.709000 893639 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 893713 closing signal SIGTERM
W1019 16:14:33.709000 893639 torch/distributed/elastic
``` 

## OS

```
Linux node-1 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by BadrYoubiIdrissi** [comment]
Thank you for bringing this to our attention ! We will add a script to download tokenizers to make it easier to run out of the box :)

**Comment by lrvl** [comment]
Also include data download?

**Comment by BadrYoubiIdrissi** [comment]
That is already covered in setup/download_prepare_hd_data.py

**Comment by Guangxuan-Xiao** [comment]
> Thank you for bringing this to our attention ! We will add a script to download tokenizers to make it easier to run out of the box :)

Thanks for the great release! Do you have an expected timeline for this?

**Comment by akhauriyash** [comment]
> That is already covered in setup/download_prepare_hd_data.py

Thank you for sharing the code! 

A quick question

https://github.com/facebookresearch/lingua?tab=readme-ov-file#1b-models-on-60b-dclm-tokens --> here, the models are trained on 60B DCLM tokens. Is there a script that cna help us download exactly those 60B token dataset? This would be a good starting point to enable folks to compare new models with the models listed in that table.

**Comment by mathuvu** [comment]
Thank you for your feedback! We will add the code to get the tokeniser today, so stay tuned!

**Comment by mathuvu** [comment]
Concerning dclm, we will add options to download smaller pool of data ([dclm_pools](https://huggingface.co/collections/mlfoundations/dclm-pools-669845e7bf3edea311ec3949)). So it will be easier to start training a model.

**Comment by mathuvu** [comment]
> Concerning dclm, we will add options to download smaller pool of data ([dclm_pools](https://huggingface.co/collections/mlfoundations/dclm-pools-669845e7bf3edea311ec3949)). So it will be easier to start training a model.

After looking at dclm pools, they are all for the filtering competition so not smaller than the base one. So not helpful in this case.

**Comment by mathuvu** [comment]
> Thank you for your feedback! We will add the code to get the tokeniser today, so stay tuned!

Landed in main with PR #27

**Comment by akhauriyash** [comment]
> > Concerning dclm, we will add options to download smaller pool of data ([dclm_pools](https://huggingface.co/collections/mlfoundations/dclm-pools-669845e7bf3edea311ec3949)). So it will be easier to start training a model.
> 
> After looking at dclm pools, they are all for the filtering competition so not smaller than the base one. So not helpful in this case.

hello,

thanks for letting me know, i am not very familiar with LLM pre-training so i apologize if the question is silly -- what dataset of 60B tokens was used to train the 1B models reported in the README? was it [mlfoundations/dclm-pool-1b-5x](https://huggingface.co/datasets/mlfoundations/dclm-pool-1b-5x)?

**Comment by mathuvu** [comment]
We take the full data [dlcm](https://huggingface.co/datasets/mlfoundations/dclm-baseline-1.0), but only train on the first 60B tokens for the 1B size model.

**Comment by akhauriyash** [comment]
Thanks for your response, I suppose then adding to the download_prepare_hf_data the following in download_dataset:

```
    if "dclm" in repo_id:
        allow_patterns = [
            "global-shard_01_of_10/*",
        ]
```

will allow us to download approximately 400B tokens (10% of the 4 trillion token dataset), to save space and compute, which hopefully correspond to the first 60B that is used in the right order.

**Comment by mathuvu** [comment]
Added the option in PR #33, which will be merged soon. The data has a size on disk ~2T instead of the 20T compare to the full dclm-baseline data.

**Comment by akhauriyash** [comment]
thanks -- this is really helpful
